version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Rat@54321
      MYSQL_DATABASE: punching_app
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./punching_app.sql:/docker-entrypoint-initdb.d/punching_app.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    image: devbratsardar/punching_app:latest
    container_name: flask-app
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: Rat@54321
      DB_NAME: punching_app
    volumes:
      - .:/app

volumes:
  db_data:
