# ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: punchapp
data:
  MYSQL_DATABASE: punching_app
  DB_HOST: mysql
  DB_USER: root
  DB_NAME: punching_app

---

# ConfigMap for the DB Init Script
apiVersion: v1
kind: ConfigMap
metadata:
  name: init-db-script
  namespace: punchapp
data:
  punching_app.sql: |
    -- MySQL dump 10.13  Distrib 8.0.43, for Linux (x86_64)
    -- Host: localhost    Database: punching_app
    -- ------------------------------------------------------
    -- Server version 8.0.43

    DROP TABLE IF EXISTS `employees`;
    CREATE TABLE `employees` (
      `id` int NOT NULL AUTO_INCREMENT,
      `name` varchar(255) NOT NULL,
      PRIMARY KEY (`id`)
    ) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

    INSERT INTO `employees` VALUES (1,'dev');

    DROP TABLE IF EXISTS `punches`;
    CREATE TABLE `punches` (
      `id` int NOT NULL AUTO_INCREMENT,
      `employee_id` int NOT NULL,
      `punch_type` varchar(10) NOT NULL,
      `punch_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
      PRIMARY KEY (`id`)
    ) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

    INSERT INTO `punches` VALUES (1,1,'in','2025-10-16 10:14:39'),(2,1,'out','2025-10-16 10:15:12');
